config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  
  devise_for :users,
    controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" },
    path: "/",
    path_names: { sign_in: "login", sign_out: "logout", sign_up: "signup", password: "reset" },
    skip: :passwords

  devise_scope :user do
    get "forgot-password", to: "users/passwords#new", as: "new_user_password"
    get "reset", to: "users/passwords#edit", as: "edit_user_password"
    patch "reset", to: "users/passwords#update", as: "user_password"
    put "reset", to: "users/passwords#update", as: nil
    post "reset", to: "users/passwords#create", as: nil
  end

  resources :users, only: %i[ show index ]
  
  resources :posts, except: %i[ index new edit update ]
  resource :follow, only: %i[ create destroy ]
  resource :like, only: %i[ create destroy ]
  resources :comments, only: %i[ create destroy ]
  
  #####

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true, length: { minimum: 3 }

  belongs_to :author, class_name: :User

  has_many :likes
  has_many :comments, -> { order "created_at DESC" }

  scope :sort_desc, -> { order("created_at DESC") }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ show destroy ]
  before_action :is_authorised, only: %i[ destroy ]

  # GET /posts
  def index
    @posts = Post.sort_desc
  end

  # GET /posts/1
  def show
    @comments = @post.comments.all
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      turbo_stream
    else
      render partial: 'posts/form', locals: { post: @post }, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy!
    redirect_to user_url(current_user), notice: "Post was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body).to_h.merge({ author: current_user })
    end

    def is_authorised
      if current_user != @post.author
        head :forbidden
        return
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= turbo_frame_tag "new-post" do %>
  <%= form_with(model: post) do |form| %>
    <% if post.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.text_area :body %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Body:</strong>
    <% if defined?(post_link) && post_link %>
      <%= link_to post.body, post_path(post) %>
    <% else %>
      <%= post.body %>
    <% end %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= link_to post.author.name, user_path(post.author) %>
  </p>

  <%= render "likes/like_button", post: post %>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.replace "new-post" do %>
  <%= render "posts/form", post: Post.new %>
<% end %>

<%= turbo_stream.prepend "posts" do %>
  <%= render @post, post_link: true %>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= render "posts/form", post: Post.new %>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post, post_link: true %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div>
  <%= button_to "Delete post", @post, method: :delete %>
</div>

<h2>Comments</h2>

<%= render 'comments/form', comment: @post.comments.new %>

<div id="comments">
  <% if @comments.any? %>
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
  <% else %>
    <p>Be the first to leave a comment.</p>
  <% end %>
</div>